version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - gdal-bin
    - gdal-data
    - libgdal-dev
    - python3-gdal

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
