version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

sphinx:
   configuration: docs/source/conf.py

conda:
  environment: environment_readthedocs.yml

formats:
  - pdf

python:
  install:
  - requirements: requirements_readthedocs.txt
